[build]
  command = "ng build --prod"
  publish = "sandbox"  # The directory where your build output is located

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-angular"
